version: "3.8"

networks:
  backend:
    driver: bridge

services:
  nginx:
      container_name: nginx
      image: nginx:1
      restart: unless-stopped
      ports:
        - 8080:80
      networks:
          - backend
      depends_on:
          - user_management
      volumes:
        - ./src/nginx/development/nginx.conf:/etc/nginx/nginx.conf:rw
        - ./src/nginx/development/api_gateway.conf:/etc/nginx/api_gateway.conf:rw
        - ./src/nginx/development/api_conf.d/:/etc/nginx/api_conf.d/:rw
  user_management:
    container_name: user_management
    build:
      context: ./src/user_management/
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src/user_management:/app
    expose:
      - 3010
    networks:
      - backend
      - db
    env_file:
      - ./src/user_management/.env
    environment:
      - HOST=http://localhost/user_management
      - PORT=3010
      - DATABASE_URL=http://coordinator1:8529,http://coordinator2:8529,http://coordinator3:8529
    depends_on:
      - coordinator1
    restart: unless-stopped
